// AUTO-GENERATED by Grimoire Admin -- 2026-04-24T14:55:42.181Z
window.POSTS_DATA = [
  {
    "id": 1,
    "path": "eojava/002-libgdx-setup.md",
    "project": "eojava",
    "projectLabel": "EOJava",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  },
  {
    "id": 2,
    "path": "eojava/003-login-screen.md",
    "project": "eojava",
    "projectLabel": "EOJava",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  },
  {
    "id": 3,
    "path": "shards-of-eternity/001-overview.md",
    "project": "shards-of-eternity",
    "projectLabel": "Shards of Eternity",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  },
  {
    "id": 4,
    "path": "gearfall-online/001-world-design.md",
    "project": "gearfall-online",
    "projectLabel": "Gearfall Online",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  },
  {
    "id": 5,
    "path": "eoengine/001-architecture.md",
    "project": "eoengine",
    "projectLabel": "EOEngine",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  },
  {
    "id": 6,
    "path": "eocobra/001-revisited.md",
    "project": "eocobra",
    "projectLabel": "EOCobra",
    "title": "placeholder",
    "date": "2026-04-22",
    "tags": [
      "placeholder"
    ],
    "md": "placeholder"
  }
];
