// AUTO-GENERATED by Grimoire Admin -- 2026-04-24T14:56:48.758Z
window.POSTS_DATA = [
  {
    "id": 1,
    "path": "shards-of-eternity/20260424-test-notes.md",
    "project": "shards-of-eternity",
    "projectLabel": "Shards of Eternity",
    "title": "Test Notes",
    "date": "2026-04-24",
    "tags": [],
    "md": "test"
  }
];
