// AUTO-GENERATED by Grimoire Admin -- 2026-04-24T15:17:47.278Z
window.PROJECTS = [
  {
    "slug": "shards-of-eternity",
    "label": "Shards of Eternity",
    "desc": "placeholder",
    "status": "In Progress",
    "lang": "HTML/CSS | TYPESCRIPT | C++",
    "type": "EO Server",
    "github": "#"
  },
  {
    "slug": "eoengine",
    "label": "EOEngine",
    "desc": "placeholder",
    "status": "Active",
    "lang": "C / C++",
    "type": "Library",
    "github": "#"
  },
  {
    "slug": "eocobra",
    "label": "EOCobra",
    "desc": "placeholder",
    "status": "In Progress",
    "lang": "C++ / Lua",
    "type": "EO Client",
    "github": "#"
  },
  {
    "slug": "eojava",
    "label": "EOJava",
    "desc": "placeholder",
    "status": "Active",
    "lang": "Java",
    "type": "EO Client",
    "github": "#"
  },
  {
    "slug": "gearfall-online",
    "label": "Gearfall Online",
    "desc": "placeholder",
    "status": "Planning",
    "lang": "C++ / EOEngine",
    "type": "MMORPG",
    "github": "#"
  }
];
