'use strict';
/**
 * build.js -- Ghoul's Grimoire static site builder
 *
 * Reads all posts/*.md files, generates:
 *   js/posts-data.js     (all post content as a JS global)
 *   js/projects-data.js  (project list from data/projects.json)
 *
 * Run after editing posts in the admin:
 *   node build.js
 *
 * Then upload the site folder to your host.
 */

const fs   = require('fs');
const path = require('path');
const ROOT = __dirname;

/* ---- Frontmatter parser ------------------------------------ */
function parseFrontmatter(raw) {
  const meta = { title:'', date:'', project:'', projectLabel:'', tags:[] };
  const parts = raw.split(/^---\s*$/m);
  let body = raw;
  if (parts.length >= 3) {
    const fm = parts[1];
    body = parts.slice(2).join('---').trim();
    fm.split('\n').forEach(line => {
      const m = line.match(/^(\w+):\s*"?([^"]*?)"?\s*$/);
      if (!m) return;
      const [, key, val] = m;
      if (key === 'tags') meta.tags = val.split(',').map(t => t.trim()).filter(Boolean);
      else meta[key] = val.trim();
    });
  }
  return { meta, body };
}

/* ---- Scan posts/ directory --------------------------------- */
function scanPosts() {
  const postsDir = path.join(ROOT, 'posts');
  const results  = [];
  if (!fs.existsSync(postsDir)) return results;

  const dirs = fs.readdirSync(postsDir)
    .filter(d => fs.statSync(path.join(postsDir, d)).isDirectory());

  let id = 1;
  dirs.forEach(project => {
    const projDir = path.join(postsDir, project);
    const files   = fs.readdirSync(projDir).filter(f => f.endsWith('.md'));
    files.forEach(file => {
      try {
        const raw          = fs.readFileSync(path.join(projDir, file), 'utf8');
        const { meta, body } = parseFrontmatter(raw);
        results.push({
          id:           id++,
          path:         project + '/' + file,
          project,
          filename:     file,
          projectLabel: meta.projectLabel || project,
          title:        meta.title || file.replace(/\.md$/, ''),
          date:         meta.date || '',
          tags:         meta.tags || [],
          md:           body
        });
      } catch (e) {
        console.warn('  WARN: could not read', file, e.message);
      }
    });
  });

  results.sort((a, b) => new Date(b.date) - new Date(a.date));
  return results;
}

/* ---- Read projects ----------------------------------------- */
function readProjects() {
  const fp = path.join(ROOT, 'data', 'projects.json');
  try { return JSON.parse(fs.readFileSync(fp, 'utf8')); }
  catch (e) { console.warn('  WARN: could not read data/projects.json'); return []; }
}

/* ---- Build ------------------------------------------------- */
const posts    = scanPosts();
const projects = readProjects();
const ts       = new Date().toISOString();

fs.writeFileSync(
  path.join(ROOT, 'js', 'posts-data.js'),
  `// Generated by build.js -- ${ts}\nwindow.POSTS_DATA = ${JSON.stringify(posts, null, 2)};\n`,
  'utf8'
);

fs.writeFileSync(
  path.join(ROOT, 'js', 'projects-data.js'),
  `// Generated by build.js -- ${ts}\nwindow.PROJECTS = ${JSON.stringify(projects, null, 2)};\n`,
  'utf8'
);

console.log('');
console.log('  Grimoire Build');
console.log('  --------------');
console.log('  Posts:    ' + posts.length);
console.log('  Projects: ' + projects.length);
console.log('  → js/posts-data.js');
console.log('  → js/projects-data.js');
console.log('');
console.log('  Upload these folders to public_html:');
console.log('  css/  js/  posts/  projects/  assets/');
console.log('  And these files:');
console.log('  index.html  about.html  resources.html');
console.log('');
